Add MangaOwl
Paperback-iOS/h-extensions pull request #25
Opened 2021-04-10 02:48 UTC by PythonCoderAS

Reference: https://github.com/Paperback-iOS/extensions-promises/pull/173

2021-04-10 02:49 UTC, PythonCoderAS commented
@ConradWeiser @DanielKovalevich PR has been transferred here.

2021-04-11 16:00 UTC, ConradWeiser commented
I was a little surprised when the home sections and search worked fine, but loading up titles failed.
It took me a few moments to realize that you gave it the cloudflare tag, and after a cloudflare bypass, the source worked great! 

It may confuse a lot of people who don’t know what’s going on. May I suggest trying to determine if a request failed due to cloudflare, and then ‘throw’ an error in human-readable test that they should do a bypass? You should be able to access headers and the http status from the response objects

That way once the error snack shows up, it comes with instructions on how to fix it.

Besides that, the code review is acceptable from any major issues that I see right away, and the on-device test works fine!

2021-04-11 16:13 UTC, PythonCoderAS commented
Does the other cloudflare sources not have the same problem? Furthermore, throwing my own errors shows a generic "Error Logged" toast

2021-04-11 17:10 UTC, ConradWeiser commented
A majority of all cloudflare sources I've seen show absolutely nothing. They have 0% functionality. 
Yours has 40% functionality, which is pretty neat!

In the future whenever automatic-cloudflare-handling is added, you likely won't have to throw a unique error anymore. Until that's implemented though, because your source operates as a slight outlier, it may be a good idea to put in for now.

2021-04-11 17:11 UTC, ConradWeiser submitted a review, later dismissed
Another extension-developer needs to review and submit the merge - My vote is only half of the process. Find someone else to give it a look, if they agree, this should be all set

2021-04-11 18:37 UTC, AdrienSeon requested changes

2021-04-11 18:37 UTC, AdrienSeon commented on src/MangaOwl/MangaOwl.ts
> +    async searchRequest(query: SearchRequest, metadata: any): Promise<PagedResults> {
Same as getViewMoreItems, if the search results are bigger than a page, the function will not fetch the second page and the user will only have access to a fraction of the results.

2021-04-11 18:37 UTC, AdrienSeon commented on src/MangaOwl/MangaOwl.ts
> +    async filterUpdatedManga(mangaUpdatesFoundCallback: (updates: MangaUpdates) => void, time: Date, ids: string[]): Promise<void> {
I'm not sure I'm understanding everything that is happening here but if @ConradWeiser validated it, it's ok for me.

2021-04-11 22:04 UTC, AdrienSeon commented on src/MangaOwl/MangaOwl.ts
> +    async filterUpdatedManga(mangaUpdatesFoundCallback: (updates: MangaUpdates) => void, time: Date, ids: string[]): Promise<void> {
For reference, the following test should be satisfied if there is at least 1 update for the selected manga in the time frame chosen in the test: `expect(updates[0].ids, "No updates").to.not.be.empty;`

The current test:
`expect(updates[0], "No updates").to.not.be.empty;` used in many sources unfortunately, does not give an accurate response as to if there _is_ an update for this manga in the chosen time frame.
It will pass if the callback is fired and an updates array is returned, even though the `ids` array is empty.

@Paperback-iOS/extension-devs

2021-04-11 22:08 UTC, PythonCoderAS commented on src/MangaOwl/MangaOwl.ts
> +    async filterUpdatedManga(mangaUpdatesFoundCallback: (updates: MangaUpdates) => void, time: Date, ids: string[]): Promise<void> {
This is the new test, and it should work, right?

https://github.com/Paperback-iOS/h-extensions/blob/77d8d7d23bc13d845cfe84f864b822de34176e58/src/tests/MangaOwl.test.ts#L87-L93

2021-04-11 22:17 UTC, AdrienSeon commented on src/MangaOwl/MangaOwl.ts
> +    async filterUpdatedManga(mangaUpdatesFoundCallback: (updates: MangaUpdates) => void, time: Date, ids: string[]): Promise<void> {
Yes, it could even replace the one on line 91 but it's not important, it's good as is.
And yes if this test passes, notifications should work.
I'm not at a computer anymore though, it's late, i will test the changes tomorrow or another dev can take a look at it while I'm sleeping.
Thank you for the fixes 👍

2021-04-12 22:29 UTC, AdrienSeon commented on src/MangaOwl/MangaOwl.ts
> +    async getViewMoreItems(homepageSectionId: string, metadata: any): Promise<PagedResults> {
This does not seem to be resolved as per the last [7e04b7b](https://github.com/Paperback-iOS/h-extensions/pull/25/commits/7e04b7b5b70c3dcac89e0e041c05a825423eb8ce) commit.
In app the additional pages are not loading.
In testing, we can see that the result of the request to page 3 is the same as the one on page 1
I can invite you to not blindly trust the unit tests that are still in development (or try to improve them) and explore the results of each request through console.log() or a js debugger to prevent pushing commits not finalized.

You can change the view more unit test that you are using by this one that is a bit more developed if you want to observe more than what the actual unit test you're using is giving you:
```js
    it("Testing view more", async () => {
        const results = await wrapper.getViewMoreItems(source, "lastest", {}, 1);
        const resultsWithPagedData = await wrapper.getViewMoreItems(source, "lastest", {}, 3);

        expect(results, "No results for page 1 for this section").to.exist;
        expect(resultsWithPagedData, "No results for page 3 for this section").to.exist;
        expect(resultsWithPagedData, "Page 1 and page 1+2+3 and the same").to.not.eql(results);

        const data = results![0];

        expect(data.id, "No ID present").to.exist;
        expect(data.image, "No image present").to.exist;
        expect(data.title.text, "No title present").to.exist;
    })
```

2021-04-12 22:30 UTC, AdrienSeon commented on src/MangaOwl/MangaOwl.ts
> +    async searchRequest(query: SearchRequest, metadata: any): Promise<PagedResults> {
This does not seem to be resolved as per the last [7e04b7b](https://github.com/Paperback-iOS/h-extensions/pull/25/commits/7e04b7b5b70c3dcac89e0e041c05a825423eb8ce) commit.
In app the additional pages are not loading.

2021-04-13 00:18 UTC, PythonCoderAS commented on src/MangaOwl/MangaOwl.ts
> +    async searchRequest(query: SearchRequest, metadata: any): Promise<PagedResults> {
I don't understand why. My code should be working, it's not like I made a mistake, but there is no loading indicator telling me that anything is happening.

2021-04-13 07:04 UTC, Aur0raN reviewed
Tested the source in-app with the latest version, the view-more function works now. As for title names not being escaped, 
`    decodeHTMLEntity(str: string): string {
        return str.replace(/&#(\d+);/g, function (match, dec) {
            return String.fromCharCode(dec);
        })
    }`
   This could be used as discussed with GameFuzzy earlier to fix that issue.
    
  I haven't come across any other issues, I've read a few mangas on the source and it seems good to go!
  
  The only thing would be to advise users to Cloudflare bypass before accessing titles as the site only uses Cloudflare when loading a title instead of when entering the site.

2021-04-13 11:54 UTC, PythonCoderAS commented
> The only thing would be to advise users to Cloudflare bypass before accessing titles as the site only uses Cloudflare when loading a title instead of when entering the site.

That's what the "Cloudflare" tag is for.

2021-04-13 20:48 UTC, AdrienSeon approved these changes

2021-04-13 20:48 UTC, merged

2021-04-13 20:49 UTC, AdrienSeon commented
Merged !
Thank you for your work @PythonCoderAS