[MangaOwl] Fix issue with chapterList if it was empty and other minor bugs
Paperback-iOS/h-extensions pull request #36
Opened 2021-04-27 12:29 UTC by PythonCoderAS

I forgot that for whatever reason empty arrays are truthy in JavaScript, which has to be one of the most confusing things/

2021-04-29 22:40 UTC, ConradWeiser requested changes

2021-04-29 22:40 UTC, ConradWeiser commented on src/MangaOwl/MangaOwlParser.ts
> +                        chapNum = Number(match[1])
- Ensure that `match[1]` exists before trying to reference it.
- Ensure that `Number(match[1])` is not NaN before trying to apply it as the chapNum

2021-04-29 22:40 UTC, ConradWeiser commented on src/MangaOwl/MangaOwlParser.ts
> +                        chapterObj.time = new Date(Date.UTC(Number(dateParts[2]), Number(dateParts[0]) - 1, Number(dateParts[1])));
You're trying to do a lot of Number casts here, which is fine if that's how it logically needs to happen.
Be sure that none of these is `NaN` before you start trying to do operations on them, though. Handle the error here gracefully, rather than having the app simply log problems.

2021-04-29 22:40 UTC, ConradWeiser commented on src/MangaOwl/MangaOwlParser.ts
>      getPart($: CheerioStatic, element: CheerioElement, partsArr: (string | null)[], index: number) {
Try to get into the habit of attaching a return type to function signatures.

2021-04-29 22:40 UTC, ConradWeiser commented on src/MangaOwl/MangaOwlParser.ts
>              const title = $("label.chapter-title", element).text().trim();
When it comes to parsing, don't be afraid of null coalescing. If a title has the possibly of being undefined, postfix a `?? ""` where applicable

2021-04-30 11:42 UTC, PythonCoderAS commented on src/MangaOwl/MangaOwlParser.ts
>              const title = $("label.chapter-title", element).text().trim();
The title cannot be undefined. Cheerio will return an empty string on the `text()` method if the selector is empty.

2021-04-30 11:48 UTC, PythonCoderAS commented on src/MangaOwl/MangaOwlParser.ts
>      getPart($: CheerioStatic, element: CheerioElement, partsArr: (string | null)[], index: number) {
The return type isn't really needed in these instances, because I declare a `Chapter[]` at the very beginning, and then return it at the end.

2021-04-30 15:30 UTC, ConradWeiser commented on src/MangaOwl/MangaOwlParser.ts
>              const title = $("label.chapter-title", element).text().trim();
I understand - This is an overall comment as there's quite a few places in the source where things can still be null. There's no need to change the line mentioned here.

2021-04-30 15:30 UTC, ConradWeiser approved these changes

2021-05-10 17:12 UTC, merged