Add HentaiHere
Paperback-iOS/h-extensions pull request #52
Opened 2021-05-09 09:27 UTC by TheNetsky

Initial PR

2021-05-09 09:43 UTC, Aur0raN reviewed
Tested on your repo and the code looks good aswell! Waiting for someone to give an in-depth review for approval!

2021-05-10 16:35 UTC, ConradWeiser requested changes

2021-05-10 16:35 UTC, ConradWeiser commented on src/HentaiHere/HentaiHereParser.ts
> +  titles.push(decodeHTMLEntity(titleContext.text().replace($("span.mngType", titleContext).text(), "").trim()));
When either of the `.text()` calls here are `""` because there was a parsing error, do you want to continue processing and show something in the app which is incorrect? Or would you prefer to throw an error here and let the app know there was an issue. (A good throw text so the app logs are useful) 

You could convince me that either way is fine, merely wanted to bring it up

2021-05-10 16:35 UTC, ConradWeiser commented on src/HentaiHere/HentaiHereParser.ts
> +  const image = $("img", "div#cover").attr('src') ?? "";
Is there a 'default' image you can display if this doesn't work? A hardcoded JPG url for a 'No image available' graphic so that people understand what's going on here or something.

2021-05-10 16:35 UTC, ConradWeiser commented on src/HentaiHere/HentaiHereParser.ts
> +    arrayTags.push({ id: id, label: label });
If either the label or ID is an empty string, do not push it to the tag list

2021-05-10 16:35 UTC, ConradWeiser commented on src/HentaiHere/HentaiHereParser.ts
> +  const customDescription = `Description \n${description}\n\nTags \n${arrayTags.map(t => t.label).join(", ")}`
If a description fails to parse on line 29, why not have this list `"No description available" or something of the sort? I really like what you did with the tags here!

2021-05-10 16:35 UTC, ConradWeiser commented on src/HentaiHere/HentaiHereParser.ts
> +    const date = new Date(Date.now() - 2208986640000); // *Lennyface*
Are you sure?

2021-05-12 07:16 UTC, TheNetsky commented on src/HentaiHere/HentaiHereParser.ts
> +    const id = String($("a", c).attr('href')?.split(`/m/${mangaId}/`)[1]?.split("/")[1] ?? "");
I've reworked this bit, hopefully it's a bit more failproof now!

2021-05-12 07:17 UTC, TheNetsky commented on src/HentaiHere/HentaiHereParser.ts
> +  const obj = JSON.parse(/var rff_imageList = (.*);/.exec(data)?.[1] ?? "");
Reworked  this part as well!

2021-05-15 21:15 UTC, AdrienSeon approved these changes
Great job overall, seems to work great on my end, some small comments but nothing blocking the approval!

2021-05-15 21:15 UTC, AdrienSeon commented on src/tests/HentaiHere.test.ts
> +        expect(results, "No results whatsoever for this section").to.exist
Is the same line as above, maybe a to.not.be.empty would be useful to prevent the next line to fail since you used `!` to bypass the undefined possibility.

2021-05-15 21:15 UTC, AdrienSeon commented on src/tests/HentaiHere.test.ts
> +        expect(results, "No results whatsoever for this section").to.exist
Is the same line as above, maybe a to.not.be.empty would be useful to prevent the next line to fail since you used `!` to bypass the undefined possibility.

2021-05-15 21:15 UTC, AdrienSeon commented on src/tests/HentaiHere.test.ts
> +        expect(results, "No results whatsoever for this section").to.exist
Is the same line as above, maybe a to.not.be.empty would be useful to prevent the next line to fail since you used `!` to bypass the undefined possibility.

2021-05-15 21:15 UTC, AdrienSeon commented on src/HentaiHere/HentaiHereParser.ts
> +}
The tag Id returned seems a bit weird to me, is it on purpose?
<img width="419" alt="image" src="https://user-images.githubusercontent.com/1227722/118378244-b4710f00-b5d2-11eb-8576-1bf00ffb1b49.png">
If you wanted the tag id to be the whole tag URL maybe `https://hentaihere.com/search/T34` would be better to match [the website](https://hentaihere.com/search/T34)?

2021-05-15 22:06 UTC, AdrienSeon approved these changes

2021-05-16 04:55 UTC, ConradWeiser approved these changes

2021-05-16 04:55 UTC, merged